-- Lisää INSERT INTO lauseet tähän tiedostoon
INSERT INTO user_account (user_accountid, username, email, password, usertype, firstname, lastname, description) VALUES (DEFAULT, 'john@usa.com', 'john@usa.com', 'Kalle123', '0', 'John', 'Doe', 'John on länkkäri.');
INSERT INTO band (bandid, bandname, description, bandimagepath) VALUES (DEFAULT, 'John Doe orchestra', 'Rujoa bläkkistä', 'http://www.kgkgkkg.fi/kuvatus.jpg');
INSERT INTO userband (user_accountID, bandID) VALUES (1, 1);
INSERT INTO review (user_accountID, bandID, review, stars) VALUES (1, 1, 'Ei nyt oikein lähde.', 1);
INSERT INTO genre (genreid, name) VALUES (DEFAULT, 'Rock');
INSERT INTO user_account (user_accountid, username, email, password, usertype, name, description) VALUES (DEFAULT, 'keijo@usa.com', 'keijo@usa.com', 'Kalle123', '0', 'Keijo', 'Keijo on länkkäri myöskin.');
INSERT INTO band (bandid, bandname, description, bandimagepath) VALUES (DEFAULT, 'Ranuan Rollarit', 'Gansta rap', 'http://www.kgkgkkg.fi/kuvatus.jpg');
INSERT INTO userband (user_accountID, bandID) VALUES (2, 2);
INSERT INTO review (user_accountID, bandID, review, stars) VALUES (2, 2, 'Tää on tosi hyvä!.', 5);
INSERT INTO genre (genreid, name) VALUES (DEFAULT, 'African');
INSERT INTO genre (genreid, name) VALUES (DEFAULT, 'Asian');
INSERT INTO genre (genreid, name) VALUES (DEFAULT, 'Avant-garde');
INSERT INTO genre (genreid, name) VALUES (DEFAULT, 'Blues');
INSERT INTO genre (genreid, name) VALUES (DEFAULT, 'Caribbean');
INSERT INTO genre (genreid, name) VALUES (DEFAULT, 'Classical');
INSERT INTO genre (genreid, name) VALUES (DEFAULT, 'Comedy');
INSERT INTO genre (genreid, name) VALUES (DEFAULT, 'Country');
INSERT INTO genre (genreid, name) VALUES (DEFAULT, 'Easy listening');
INSERT INTO genre (genreid, name) VALUES (DEFAULT, 'Electronic');
INSERT INTO genre (genreid, name) VALUES (DEFAULT, 'Folk');
INSERT INTO genre (genreid, name) VALUES (DEFAULT, 'Gospel');
INSERT INTO genre (genreid, name) VALUES (DEFAULT, 'Hip hop');
INSERT INTO genre (genreid, name) VALUES (DEFAULT, 'Jazz');
INSERT INTO genre (genreid, name) VALUES (DEFAULT, 'Latin');
INSERT INTO genre (genreid, name) VALUES (DEFAULT, 'Pop');
INSERT INTO genre (genreid, name) VALUES (DEFAULT, 'R&B and soul');
INSERT INTO genre (genreid, name) VALUES (DEFAULT, 'Rock');
