-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS bands CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS usersinbands CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
