-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS user_account CASCADE;
DROP TABLE IF EXISTS band CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS bandgenre CASCADE;
DROP TABLE IF EXISTS userband CASCADE;
DROP TABLE IF EXISTS review CASCADE;
